### ISSUE TITLE
Migrate Robofriends App From Create-React-App to Vite

### ISSUE THREAD

**Issue by jmdonovan0227** [jmdonovan0227/robofriends#1]
## Description
Current Robofriends App is built using create-react-app, which is deprecated. App is going to be moved to a currently maintained build tool, Vite for performance and security reasons.

## Acceptance Criteria
- [x] A new vite project has been created with the same files as current project.
- [x] All code is transferred to vite project and dependencies are updated.
- [x] There is no regression in functionality as compared to current robofriends app.
- [x] Updated robofriends app can still be viewed on github pages hosted link.
## Tasks
1) Create a new vite project with all files contained within current Robofriends project.
2) Transfer all code from current robofriends app to vite project.
3) Update dependencies.
4) Ensure project still displays a scrollable window, contact cards for each robot, and still filters robots through use of search bar.
5) Rebuild robofriends app for github pages.

**Comment by jmdonovan0227** [comment]
All tasks completed. Robofriends app is now using the vite build tool instead of create-react-app and does not currently show any regression at website link.
