### ISSUE TITLE
Convert Robofriends App to PWA

### ISSUE THREAD

**Issue by jmdonovan0227** [jmdonovan0227/robofriends#10]
## Description
App needs to be converted to PWA to improve user experience by providing a mobile like experience including offline functionality and installability for users that frequently visit Robofriends application.

## Acceptance Criteria
- [x] Robofriends application provides offline functionality by allowing users to view robots even if there is not internet connection.
- [x] Robofriends application allows user to download the application, so they can quickly navigate to the webpage.
- [x] Robofriends application does not show any signs of regression in functionality as compared to current application.

## Tasks
1) Install necessary packages for pwa implementation.
2) Create an app manifest with all necessary icons needed for installability.
3) Create a runtime cache to allow robots API call to be cached, so the user can still view and search for robots while application is offline.
4) Merge changes into development then main.
5) Rebuild gh-pages and test for any regression in functionality.
6) Test performance, accessibility, and pwa related metrics with Lighthouse.

**Comment by jmdonovan0227** [comment]
All tasks have been completed for this issue. There will need to be a following issue for performance improvement and testing.
