### ISSUE TITLE
Test React Components, Actions, and Reducers in Robofriends Application

### ISSUE THREAD

**Issue by jmdonovan0227** [jmdonovan0227/robofriends#33]
## Description
We need to test our stateless components, containers, actions, and reducers to increase confidence Robofriends will work for users as expected.

## Acceptance Criteria
- [ ] All components, actions, and reducers are being tested
- [ ] Aim for 70 percent coverage or higher, so we can cover critical functionality, but of course higher is always better :).
- [ ] Merge changes into development and then main, but make sure to install dependencies as developer dependencies, we need these test case in our development environment not for production!

# Tasks
1) Install all dependencies to test Robofriends with Jest and React Testing Library as dev dependencies.
2) Create a test folder with test files for each component, actions, and reducers.
3) Verify all test cases pass and verify coverage of test cases.
4) Merge changes into development and then main.
5) Verify that there is no regression in current application functionality.
