### ISSUE TITLE
Implement Redux in Robofriends Application To Simplify State Management

### ISSUE THREAD

**Issue by jmdonovan0227** [jmdonovan0227/robofriends#4]
## Description
While current Robofriends App includes a small amount of state to manage, the application needs to include a state management solution as the application grows larger, which is why Redux can be a great option to simplify handling of state and making scaling the application easier as it grows over time.

## Acceptance Criteria
- [x] Robofriends has redux package installed.
- [x] Robofriends has created a redux store to manage state in application and defines actions and reducer functions to update store.
- [x] Robofriends shows no regression in functionality after implementing redux.

## Tasks
1) Install redux in Robofriends application.
2) Determine what the key actions are that will go through reducer functions and update the store and the view.
3) Make sure to separate logic for actions and reducers files are split up as much as possible to simplify redux implementation for easy understanding.

**Comment by jmdonovan0227** [comment]
All tasks completed and all acceptance criteria has been met as of merge request #6. Issue closed.
